gitannex:
  #build: ./annex-service
  image: annex
  environment:
    NAME_OF_REPOS: "The Repository"
    YOUR_NAME: "Mister Anonymous"
    YOUR_EMAIL: "mister@anonymous.com"
  ports:
    - 7000:7000
  volumes:
    - ./annex-service/repos:/repos
